import os
# Azure OpenAI の API キー
STRING_IS_AZURE_OPENAI = os.environ.get('IS_AZURE_OPENAI')
AZURE_OPENAI_KEY = os.environ.get('AZURE_OPENAI_KEY')
AZURE_OPENAI_ENDPOINT = os.environ.get('AZURE_OPENAI_ENDPOINT')
AZURE_OPENAI_DEPLOYMENT_NAME = os.environ.get('AZURE_OPENAI_DEPLOYMENT_NAME')
AZURE_OPENAI_DEPLOYMENT_VERSION = os.environ.get('AZURE_OPENAI_DEPLOYMENT_VERSION')